# Generated by Django 4.2.7 on 2023-11-09 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Memeber',
            new_name='Member',
        ),
    ]
