# Generated by Django 4.2.7 on 2023-11-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_rename_memeber_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='joinedDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
